### ISSUE TITLE
Disable Vive Pro microphone in Room View

### ISSUE THREAD

**Issue by limited660** [ykeara/OpenVR-AdvancedSettings#2]
Is it possible to get an option to disable the microphone when entering Room View on the Vive Pro? Currently when you switch to Room View, it provides a very high level of side tone to the headphones which is quite annoying and can be very loud due to breathing or touching the headset.

**Comment by ykeara** [comment]
So in the vive pro the microphone is mirrored when you go into room view (tron mode)? am I correct in assuming that? 

you can use the push-to-talk feature (or push-to mute) kinda a band-aid... If you can give me any more information that would be appreciated, but TBH that sounds like a htc issue... doubt its accessible via api (directly at least)

and just for reference regular vive doesn't do any of that audio mirroring afaik... I don't know if its intentional or not. I can look into adding a global/mute in the audio settings page for mic... but it may still not fix your specific issue.

**Comment by limited660** [comment]
Yes it is mirroring the audio to the headphones and unfortunately I already have push-to-talk enabled and it still does it so I assume that is above what you can access.

**Comment by ykeara** [comment]
Yea. appears that way... especially since its headset specific. I'm going to mark the issue as closed.... may look into it again in the future if I ever get the pro headset but for now looks to be a htc/vive issue more than a steamvr issue.
